"""Generate all README languages and app descriptions from matching content schemas.

Change every docs/localization/readme/<language>.json together, then run this
script. --check rejects incomplete catalogs or README files that have drifted.
"""
import argparse
import json
from pathlib import Path
import string

ROOT = Path(__file__).resolve().parents[1]
LANGUAGES = {'en': 'English', 'ru': 'Русский', 'zh': '简体中文', 'ar': 'العربية',
             'sr': 'Српски', 'el': 'Ελληνικά', 'es': 'Español'}
REPO = 'https://github.com/sirdimitry/FaceBlur-Studio'
LINKS = dict(repo=REPO, issues=REPO + '/issues', fork=REPO + '/fork',
             maintainer='https://github.com/sirdimitry',
             win_details='docs/WINDOWS_INSTALLER.md', win_validation='docs/WINDOWS_VALIDATION.md',
             win_handoff='docs/WINDOWS_HANDOFF.md', dmg_script='scripts/build_macos_dmg.sh',
             apple_help='https://support.apple.com/en-au/102445',
             icon='AutoBlureFace_icon.png', banner='assets/banner.png',
             win_release=REPO + '/releases/tag/v1.1.28',
             mac_release=REPO + '/releases/tag/v1.1.28',
             localization='docs/LOCALIZATION.md')
WINDOWS_ASSET = REPO + '/releases/download/v1.1.28/FaceBlur-Studio-1.1.28-Windows-Setup.exe'
MAC_ASSET = REPO + '/releases/download/v1.1.28/FaceBlur_Studio_v1.1.28_Apple_Silicon.dmg'
SHA_WINDOWS = '9e4b347dd52b9d6d2eaefbf91596ec29895e393e0af6280a0440826d3280fdbb'
SHA_MAC = '9ba0cc0fd5c9dfba8a58c90ba0f4e16e2f4460efcc725131505016deb547ed1d'
SOURCE_COMMANDS = '''git clone https://github.com/sirdimitry/FaceBlur-Studio.git
cd FaceBlur-Studio
python3 -m venv venv
source venv/bin/activate
python -m pip install -r requirements.txt
python main.py'''


def filename(code):
    return 'README.md' if code == 'en' else f'README.{code}.md'


def fields(text):
    return sorted(field for literal, field, spec, conversion in string.Formatter().parse(text)
                  if field is not None)


def load_content():
    all_content = {code: json.loads((ROOT / 'docs/localization/readme' / f'{code}.json').read_text(encoding='utf-8'))
                   for code in LANGUAGES}
    english = all_content['en']
    for code, content in all_content.items():
        if content.keys() != english.keys():
            raise ValueError(f'{code}: README sections do not match English')
        for key, value in content.items():
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f'{code}: empty README block {key}')
            if fields(value) != fields(english[key]):
                raise ValueError(f'{code}: README links/placeholders differ in {key}')
    return all_content


def render(code, content):
    text = {key: value.format(**LINKS) for key, value in content.items()}
    navigation = ' · '.join('<strong>' + name + '</strong>' if language == code else
                            f'<a href="{filename(language)}">{name}</a>'
                            for language, name in LANGUAGES.items())
    result = [f'<p dir="ltr" align="center">{navigation}</p>',
              '<!-- Generated by scripts/render_readmes.py. Update all language sources together. -->']
    if code == 'ar':
        result += ['<div dir="rtl" lang="ar">']
    result += ['<p align="center"><img src="assets/banner.png" alt="FaceBlur Studio" width="100%"></p>',
               '# FaceBlur Studio', f'**{text["tagline"]}**', text['description'],
               '## ' + text['h_download'],
               f'- [{text["windows_download"]}]({WINDOWS_ASSET})\n- [{text["mac_download"]}]({MAC_ASSET})',
               text['invitation'], '> ' + text['build_note'],
               '## ' + text['h_screenshot'],
               f'![{text["screenshot_alt"]}](assets/faceblur-studio-1.1.23.png)',
               '## ' + text['h_features'],
               '\n'.join('- ' + text[f'f{index}'] for index in range(1, 10)), text['caution'],
               '## ' + text['h_install'], text['win_install'], text['win_limits'],
               f'Windows SHA-256: `{SHA_WINDOWS}`', text['mac_install'], text['mac_limits'],
               f'macOS SHA-256: `{SHA_MAC}`', '### ' + text['source_heading'], text['source_intro']]
    if code == 'ar':
        result += ['<div dir="ltr">']
    result += ['```bash\n' + SOURCE_COMMANDS + '\n```']
    if code == 'ar':
        result += ['</div>']
    result += [text['win_source'], '## ' + text['h_start'],
               '\n'.join(f'{index}. ' + text[f'step{index}'] for index in range(1, 4)),
               '## ' + text['h_languages'], text['language_behavior'], text['rtl_behavior'],
               '## ' + text['h_diagnostics'], text['logs_intro'],
               f'- {text["source_log"]}: `debug_app.log`\n'
               f'- {text["installed_mac"]}: `~/Library/Logs/FaceBlurStudio/debug_app.log`\n'
               f'- {text["installed_win"]}: `%LOCALAPPDATA%\\FaceBlurStudio\\Logs\\debug_app.log`',
               text['log_warning'], '## ' + text['h_contents'], text['contents'],
               '## ' + text['h_support'], text['support'], text['maintainer'],
               '## ' + text['h_license'], text['license']]
    if code == 'ar':
        result += ['</div>']
    return '\n\n'.join(result) + '\n'


def render_descriptions(content):
    sections = ['# FaceBlur Studio — application descriptions',
                '<!-- Generated from the README sources; update all languages together. -->']
    for code, name in LANGUAGES.items():
        direction = 'rtl' if code == 'ar' else 'ltr'
        sections += [f'## {name}', f'<div dir="{direction}" lang="{code}">',
                     '**' + content[code]['tagline'] + '**', content[code]['description'], '</div>']
    return '\n\n'.join(sections) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = load_content()
    outputs = {ROOT / filename(code): render(code, data) for code, data in content.items()}
    outputs[ROOT / 'docs/APP_DESCRIPTIONS.md'] = render_descriptions(content)
    stale = []
    for path, output in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != output:
                stale.append(path.name)
        else:
            path.write_text(output, encoding='utf-8')
    if stale:
        parser.error('Generated files need updating: ' + ', '.join(stale))
    print(('Checked' if args.check else 'Generated') + f' {len(outputs)} multilingual documents.')


if __name__ == '__main__':
    main()
